In [33]:
#import necessary library and modules
import numpy as np
from matplotlib import pyplot as plt

In [34]:
#input sequence
# x = [1, 2, 3, 4, 5]
# x = [-1, 5]
x = [1,2,1,1]

#impulse response
# h = [1, 2, 3, 4, 2, 1]
# h = [4, -3]
h = [1,1,2,1]

In [41]:
def my_convolution(x, h):
    # Calculate length of x and h
    l_x = len(x)
    l_h = len(h)

    print("Length of x and h are ", l_x, " and ", l_h )

    # compute length of y
    l_y = l_x + l_h -1
    print("Length of y is ", l_y)
    # Compute y using the convolution sum algorithm that we learned

    # Pad x and h to make the length to be l_y
    x_pad = np.pad(x, (0,l_y-l_x), 'constant')
    h_pad = np.pad(h, (0,l_y-l_h), 'constant')
    y = np.zeros(l_y) 

    for n in range(l_y):
        for k in range(l_y):
            if n >= k:
                y[n] = y[n] + x_pad[n-k]*h_pad[k]

    return y, l_h, l_x, l_y

In [42]:
y, l_h, l_x, l_y = my_convolution(x, h)
print('Linear convolution using convolution sum formula output response y =\n',y)

Length of x and h are  4  and  4
Length of y is  7
Linear convolution using convolution sum formula output response y =
 [1. 3. 5. 7. 5. 3. 1.]


In [43]:
# Let's use the built in linear convolution finction in Numpy

y1 = np.convolve(x, h)
print('Linear convolution using NumPy built-in function output response y=\n',y1)

Linear convolution using NumPy built-in function output response y=
 [1 3 5 7 5 3 1]


# use convolution for cross-correlation

In [44]:
# time-reverse h
h_rev = np.zeros(l_h)
for i in range(l_h):
    h_rev[l_h-1-i] = h[i]

print("h: ", h)
print("time-reversed h: ", h_rev)

h:  [1, 1, 2, 1]
time-reversed h:  [1. 2. 1. 1.]


In [47]:
# correlation using built in correlation function
y1 = np.correlate(x,h, 'full')
print('Cross correlation using NumPy correlation built-in function, y=\n',y1)

Cross correlation using NumPy correlation built-in function, y=
 [1 4 6 6 5 2 1]


In [48]:
# correlation using built in convolution function
y2 = np.convolve(x, h_rev)
print('Cross correlation using NumPy convolution built-in function, y=\n',y2)

Cross correlation using NumPy convolution built-in function, y=
 [1. 4. 6. 6. 5. 2. 1.]


In [49]:
# Now let's try using the convolution equation
y3, _, _, _ = my_convolution(x, h_rev)
print('correlation using formula,  y =\n',y3)

Length of x and h are  4  and  4
Length of y is  7
correlation using formula,  y =
 [1. 4. 6. 6. 5. 2. 1.]
